services:
  db:
    image: postgres
    networks:
      - my-bridge-network
    restart: always
    
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5432:5432"
    
  redis: 
     image: redis:6.2-alpine
     networks:
       - my-bridge-network
     ports:
       - '6379:6379' 
  
  celery:
     build: .
     networks:
       - my-bridge-network
     command: celery -b redis://redis:6379/0 -A quicktest worker -l debug 
     environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_HOST=redis
     depends_on:
       - db
       - redis
     
  web:
    build: .
    networks:
      - my-bridge-network
    command: python manage.py runserver 0.0.0.0:8000
  
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_started
        restart: true
      redis:
        condition: service_started
    restart: always
    

networks:
  my-bridge-network:
    driver: bridge
  
  
      
   
